const SPANISH_NAME_OVERRIDES: Record<string, string> = {
  "Grenada": "Granada",
  "Anguilla": "Anguila",
  "Djibouti": "Yibuti",
  "Brunei": "Brunéi",
  "Palau": "Palaos",
  "Bahamas": "Las Bahamas",
  "Gambia": "Gambia",
  "Czechia": "Chequia",
  "Cape Verde": "Cabo Verde",
  "Ivory Coast": "Costa de Marfil",
  "Timor-Leste": "Timor Oriental",
  "South Korea": "Corea del Sur",
  "North Korea": "Corea del Norte",
  "United Kingdom": "Reino Unido",
  "United States": "Estados Unidos",
  "United Arab Emirates": "Emiratos Árabes Unidos",
  "Saudi Arabia": "Arabia Saudita",
  "Vatican City": "Ciudad del Vaticano",
  "North Macedonia": "Macedonia del Norte",
  "Papua New Guinea": "Papúa Nueva Guinea",
  "New Zealand": "Nueva Zelanda",
  "South Africa": "Sudáfrica",
  "Equatorial Guinea": "Guinea Ecuatorial",
  "Solomon Islands": "Islas Salomón",
  "Marshall Islands": "Islas Marshall",
  "Faroe Islands": "Islas Feroe",
  "Saint Martin": "San Martín (parte francesa)",
  "Sint Maarten": "San Martín (parte neerlandesa)",
  "DR Congo": "República Democrática del Congo",
  "Curaçao": "Curazao",
  "Åland Islands": "Islas Åland",
  "Caribbean Netherlands": "Caribe Neerlandés",
  "Pitcairn Islands": "Islas Pitcairn",
  "Macau": "Macao",
  "Botswana": "Botsuana",
};

const COUNTRY_ALIASES: Record<string, string[]> = {
  "Grenada": ["Granada"],
  "United States": ["EEUU", "EE. UU.", "Estados Unidos de América", "USA", "US", "United States of America"],
  "Falkland Islands": ["Malvinas", "Falklands", "Islas Falkland"],
  "Netherlands": ["Holanda"],
  "United Kingdom": ["Reino Unido", "Gran Bretaña", "UK", "Great Britain"],
  "United Arab Emirates": ["Emiratos", "EAU", "UAE"],
  "Dominican Republic": ["República Dominicana", "RD"],
  "Central African Republic": ["República Centroafricana", "Centroáfrica"],
  "DR Congo": ["Congo Democrático", "Congo Kinshasa", "RDC", "RD Congo"],
  "Congo": ["República del Congo", "Congo Brazzaville"],
  "Czechia": ["República Checa"],
  "Myanmar": ["Birmania"],
  "Eswatini": ["Suazilandia", "Swaziland"],
  "Timor-Leste": ["Timor", "Timor Leste"],
  "Vatican City": ["Vaticano", "Santa Sede", "Holy See"],
  "Palestine": ["Estado de Palestina"],
  "Saudi Arabia": ["Arabia Saudita", "Arabia"],
  "Cape Verde": ["Cabo Verde"],
  "Ivory Coast": ["Costa de Marfil", "Côte d'Ivoire"],
  "South Korea": ["Corea del Sur", "República de Corea"],
  "North Korea": ["Corea del Norte", "RPDC"],
  "Russia": ["Federación Rusa"],
  "Bolivia": ["Estado Plurinacional de Bolivia"],
  "Venezuela": ["República Bolivariana de Venezuela"],
  "Syria": ["Siria", "República Árabe Siria"],
  "Laos": ["República Democrática Popular Lao"],
  "Vietnam": ["Viet Nam"],
  "Brunei": ["Brunéi", "Brunei Darussalam"],
  "Saint Martin": ["San Martín", "Saint-Martin", "San Martin francés"],
  "Sint Maarten": ["San Martín", "Saint Maarten", "Saint Marteen", "Sint Martin", "San Martin neerlandés"],
  "Saint Barthélemy": ["San Bartolomé", "St Barth", "St. Barthélemy"],
  "Saint Kitts and Nevis": ["San Cristóbal y Nieves", "Saint Kitts"],
  "Saint Vincent and the Grenadines": ["San Vicente", "San Vicente y las Granadinas", "Granadinas"],
  "Cocos (Keeling) Islands": ["Islas Cocos", "Islas Keeling", "Cocos"],
  "Faroe Islands": ["Islas Feroe", "Feroe", "Faroes"],
  "British Virgin Islands": ["Islas Vírgenes Británicas", "Vírgenes Británicas"],
  "United States Virgin Islands": ["Islas Vírgenes Estadounidenses", "Vírgenes de Estados Unidos"],
  "Türkiye": ["Turquía", "Turkey"],
  "Bahamas": ["Las Bahamas", "The Bahamas"],
  "Bahrain": ["Baréin", "Bahrein"],
  "Belarus": ["Bielorrusia", "Belarús"],
  "Bosnia and Herzegovina": ["Bosnia", "Bosnia Herzegovina"],
  "Djibouti": ["Yibuti"],
  "Gambia": ["La Gambia", "The Gambia"],
  "Kyrgyzstan": ["Kirguistán", "Kirguizistán", "Kyrgyz Republic"],
  "Moldova": ["Moldavia", "República de Moldavia"],
  "North Macedonia": ["Macedonia", "Macedonia del Norte"],
  "Micronesia": ["Estados Federados de Micronesia", "FSM"],
  "Palau": ["Palaos"],
  "São Tomé and Príncipe": ["Santo Tomé y Príncipe", "Sao Tome y Principe"],
  "Tanzania": ["República Unida de Tanzania"],
  "Iran": ["República Islámica de Irán", "Persia"],
  "Taiwan": ["Taiwán", "Chinese Taipei"],
  "Hong Kong": ["Hong Kong SAR", "Hong Kong RAE"],
  "Macau": ["Macao", "Macao SAR", "Macao RAE"],
  "Réunion": ["Reunión", "Isla Reunión"],
  "Åland Islands": ["Islas Åland", "Aland", "Alandia"],
  "American Samoa": ["Samoa Americana"],
  "British Indian Ocean Territory": ["Territorio Británico del Océano Índico", "BIOT"],
  "Caribbean Netherlands": ["Caribe Neerlandés", "Bonaire, San Eustaquio y Saba", "BES Islands"],
  "Cayman Islands": ["Islas Caimán", "Caimán", "Cayman"],
  "Christmas Island": ["Isla de Navidad", "Navidad"],
  "Cook Islands": ["Islas Cook", "Cook"],
  "French Guiana": ["Guayana Francesa"],
  "French Polynesia": ["Polinesia Francesa", "Tahiti"],
  "French Southern and Antarctic Lands": ["Tierras Australes Francesas", "Territorios Australes Franceses"],
  "Heard Island and McDonald Islands": ["Islas Heard y McDonald", "Heard y McDonald"],
  "Northern Mariana Islands": ["Islas Marianas del Norte", "Marianas del Norte"],
  "Pitcairn Islands": ["Islas Pitcairn", "Pitcairn"],
  "Solomon Islands": ["Islas Salomón", "Salomón"],
  "South Georgia": ["Georgia del Sur", "Islas Georgias del Sur y Sandwich del Sur"],
  "Svalbard and Jan Mayen": ["Svalbard y Jan Mayen", "Svalbard"],
  "Turks and Caicos Islands": ["Islas Turcas y Caicos", "Turcas y Caicos", "Turks y Caicos"],
  "United States Minor Outlying Islands": ["Islas Ultramarinas Menores de Estados Unidos", "US Minor Outlying Islands"],
  "Wallis and Futuna": ["Wallis y Futuna", "Wallis", "Futuna"],
  "Western Sahara": ["Sáhara Occidental", "Sahara Occidental"],
  "Antigua and Barbuda": ["Antigua", "Barbuda"],
  "Trinidad and Tobago": ["Trinidad", "Trinidad y Tobago"],
  "Papua New Guinea": ["Papúa Nueva Guinea", "Papua"],
  "Marshall Islands": ["Islas Marshall", "Marshall"],
  "New Zealand": ["Nueva Zelanda", "Aotearoa"],
  "South Africa": ["Sudáfrica", "República de Sudáfrica", "RSA"],
  "Equatorial Guinea": ["Guinea Ecuatorial"],
  "Guinea-Bissau": ["Guinea Bisáu", "Guinea Bissau"],
  "Sierra Leone": ["Sierra Leona"],
  "Sri Lanka": ["Ceilán", "Ceylon"],
  "Thailand": ["Tailandia", "Siam"],
  "Botswana": ["Botsuana"],
};

const NON_SOVEREIGN_COUNTRIES = new Set([
  "American Samoa", "Anguilla", "Antarctica", "Aruba", "Åland Islands",
  "Bermuda", "Bouvet Island", "British Indian Ocean Territory", "British Virgin Islands",
  "Caribbean Netherlands", "Cayman Islands", "Christmas Island", "Cocos (Keeling) Islands",
  "Cook Islands", "Curaçao", "Falkland Islands", "Faroe Islands", "French Guiana",
  "French Polynesia", "French Southern and Antarctic Lands", "Gibraltar", "Greenland",
  "Guadeloupe", "Guam", "Guernsey", "Heard Island and McDonald Islands", "Hong Kong",
  "Isle of Man", "Jersey", "Kosovo", "Macau", "Martinique", "Mayotte", "Montserrat",
  "New Caledonia", "Niue", "Norfolk Island", "Northern Mariana Islands", "Pitcairn Islands",
  "Puerto Rico", "Réunion", "Saint Barthélemy", "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Martin", "Sint Maarten", "South Georgia", "Svalbard and Jan Mayen", "Taiwan",
  "Tokelau", "Turks and Caicos Islands", "United States Minor Outlying Islands",
  "United States Virgin Islands", "Wallis and Futuna", "Western Sahara",
]);

export function getSpanishCountryName(englishName: string, datasetName: string) {
  return SPANISH_NAME_OVERRIDES[englishName] || datasetName.split("(")[0].trim();
}

export function getCountryAliases(englishName: string) {
  return COUNTRY_ALIASES[englishName] || [];
}

export function isSovereignCountry(englishName: string) {
  return !NON_SOVEREIGN_COUNTRIES.has(englishName);
}
